Reorganized project files; added manifests playbook

diff --git a/rancher.yml b/rancher.yml
--- a/rancher.yml
+++ b/rancher.yml
@@ -51,7 +51,8 @@
     - name: Merge kubeconfig into local
       vars:
         kubeconfig: "{{ k3s_kubeconfig }}"
-        context: "{{ k3s_local_context }}"
+        context: "{{ k3s_cluster_name }}"
+        server: "{{ k3s_fqdns[0] }}"
       ansible.builtin.include_tasks: tasks/kubeconfig.yml
 
 - name: Install Rancher Server on K3s
@@ -74,6 +75,8 @@
         release_values:
           crds:
             enabled: true
+        wait: true
+      timeout: 300
 
     # https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster#install-the-rancher-helm-chart
     - name: Install Rancher Server Helm chart
@@ -88,6 +91,8 @@
         release_values:
           replicas: 1
           hostname: "{{ k3s_fqdns[0] }}"
+        wait: true
+      timeout: 600
 
     # https://github.com/rancher/cli
     - name: Install Rancher CLI utility
@@ -109,63 +114,96 @@
           ./rancher-v${VER}/rancher
       args:
         executable: /bin/bash
-      register: install
-      changed_when: install.rc == 0
+      register: install_cli
+      changed_when: install_cli.rc == 0
       failed_when: >-
-        install.rc != 0 and
-        install.rc != 9
+        install_cli.rc != 0 and
+        install_cli.rc != 9
 
-    - name: Log into Rancher using CLI
+    - name: Import RKE cluster using API
       # noqa risky-shell-pipe
       ansible.builtin.shell: |
         # restart Bash and load .bash_aliases
         # in order to use my custom functions
-        cat <<'EOT' | exec /bin/bash
+        cat <<'EOF' | exec /bin/bash
 
         TOKEN_DESC="Ansible session"
         ADMIN_PASS="{{ rancher_admin_pass }}"
         . .bash_aliases # loads .rancher_api
 
-        cluster="{{ rke2_local_context }}"
+        cluster="{{ rke_cluster_name }}"
         id_var="${cluster^^}_ID"
         cluster_id="${!id_var}"
 
-        [ ! "$cluster_id" ] && {
-          context="$LOCAL_SYSTEM_ID"
-        } || {
-          # RKE2 cluster already imported
-          id_var="${cluster^^}_SYSTEM_ID"
-          context="${!id_var}"
-
-          # show registration manifest URL
-          # to apply on control plane node
-          url=$(rancher_api get clusters/$cluster_id/clusterregistrationtokens | \
-            jq -r '.data[] | select(.name | startswith("crt-")) | .manifestUrl')
-          echo "MANIFEST=$url"
+        get_state() {
+          rancher_api get clusters/$cluster_id | \
+            jq -r '.state // empty'
         }
-
-        # request a long-lived token
-        token=$(get_token "CLI token")
-        rancher login "$RANCHER_URL" \
-          --skip-verify \
-          --token   "$token" \
-          --context "$context"
-
-        rancher_logout # delete $LOGIN_TOKEN
+        if [ ! "$cluster_id" ]; then
+          # RKE cluster not imported yet: import using the Rancher API
+          cluster_id=$(cat <<'EOT' | rancher_api post clusters @- | jq -r '.id // empty'
+        {
+          "import":      true,
+          "type":        "cluster",
+          "name":        "{{ rke_cluster_name }}",
+          "description": "{{ rke_cluster_desc }}"
+        }
         EOT
-      register: cli_login
+          )
+          [ "$cluster_id" ] || {
+            echo >&2 "Cluster import failed!"
+            exit 1
+          }
+          echo "Waiting for cluster state to be \"pending\"..."
+          until [ "$(get_state)" == pending ]; do sleep 1; done
+          export_variables
+        fi
+
+        if [ "$(get_state)" != active ]; then
+          # output registration manifest URL so it can be applied on control plane node
+          reg_url=$(rancher_api get "clusters/$cluster_id/clusterregistrationtokens" | \
+            jq --arg baseUrl "$RANCHER_URL" -r '.data[] |
+              select(.name == "default-token") |
+                if (.manifestUrl // "") != "" then
+                  .manifestUrl
+                elif (.token // "") != "" then
+                  "\($baseUrl)/v3/import/\(.token)_\(.clusterId).yaml"
+                else empty
+                end
+              ')
+          [ "$reg_url" ] && echo "REGISTER=$reg_url"
+        fi
+
+        # perform CLI login if not already
+        config="$HOME/.rancher/cli2.json"
+        [ -f $config ] && \
+          [ "$(jq -r '.Servers[.CurrentServer].tokenKey // empty' $config)" ] || {
+
+          # request a long-lived token
+          token=$(get_token "CLI token")
+          id_var="${cluster^^}_DEFAULT_ID"
+
+          rancher login "$RANCHER_URL" \
+            --skip-verify      \
+            --token   "$token" \
+            --context "${!id_var}"
+        }
+        rancher_logout # delete $LOGIN_TOKEN
+        EOF
+      timeout: 300
+      register: import_rke
       changed_when: true
 
-    - name: Save RKE2 registration URL
+    - name: Save RKE registration URL
       # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
       ansible.builtin.set_fact:
         # used in cluster.yml
-        rke2_reg_url: >-
-          {% set lines = cli_login.stdout_lines | select('search','^MANIFEST=') | list -%}
-          {{ lines[0].split('MANIFEST=')[1] if lines | length > 0 else '' }}
-      when: cli_login.rc == 0
+        rke_reg_url: >-
+          {% set lines = import_rke.stdout_lines | select('search','^REGISTER=') | list -%}
+          {{ lines[0].split('REGISTER=')[1] if lines | length > 0 else '' }}
+      when: import_rke.rc == 0
 
-    - name: Show RKE2 registration URL
+    - name: Show RKE registration URL
       ansible.builtin.debug:
         msg: |-
-          rke2_reg_url: "{{ rke2_reg_url if rke2_reg_url is defined else '<undefined>' }}"
+          rke_reg_url: "{{ rke_reg_url if rke_reg_url is defined else '<undefined>' }}"
diff --git a/templates/rancher.sh.j2 b/templates/rancher.sh.j2
--- a/templates/rancher.sh.j2
+++ b/templates/rancher.sh.j2
@@ -12,7 +12,9 @@ rancher_login() {
       "username":    "admin",
       "password":    "'"$1"'",
       "description": "'"${TOKEN_DESC:-SSH session}"'"
-    }' | jq -r '"\(.token // "") \(.id // "")" | ltrimstr(" ")'
+    }' | jq -r 'if type == "object" then (
+          "\(.token // "") \(.id // "")" | ltrimstr(" ")
+       ) else empty end'
 }
 
 # attempt login using bootstrap password from Kubernetes secret;
@@ -23,14 +25,24 @@ rancher_login() {
 
 # prevent Jinja2 from interpreting Go template
 {%- raw %}
-BOOTSTRAP_PASS=$(kubectl get secret -n cattle-system bootstrap-secret \
-  -o go-template='{{ .data.bootstrapPassword | base64decode }}')
+get_init_pass() {
+  kubectl get secret -n cattle-system bootstrap-secret \
+    -o go-template='{{ .data.bootstrapPassword | base64decode }}' 2> /dev/null
+}
 {%- endraw %}
+
+BOOTSTRAP_PASS=$(get_init_pass)
+if [ ! "$BOOTSTRAP_PASS" ]; then
+  echo -e "\nRancher bootstrap secret not found!"
+  echo "Waiting until Rancher is ready..."
+  until [ "$(get_init_pass)" ]; do sleep 1; done
+  BOOTSTRAP_PASS=$(get_init_pass)
+fi
 
 LOGIN_TOKEN=($(rancher_login "$BOOTSTRAP_PASS"))
 unset BOOTSTRAP_PASS
 
-if [ ! "$LOGIN_TOKEN" ]; then
+[ "$LOGIN_TOKEN" ]  && echo || {
   [ "$ADMIN_PASS" ] || {
     echo
     # prompt unless already set by Ansible
@@ -40,12 +52,12 @@ if [ ! "$LOGIN_TOKEN" ]; then
   # LOGIN_TOKEN is an array: [token, token-id]
   LOGIN_TOKEN=($(rancher_login "$ADMIN_PASS"))
   unset ADMIN_PASS
-fi
+}
 
 [ "$LOGIN_TOKEN" ] && {
   echo -e "Rancher admin login succeeded.\n"
 } || {
-  echo >&2 "Failed logging into Rancher!"
+  echo >&2 -e "Failed logging into Rancher!\n"
   return 1
 }
 
@@ -70,7 +82,8 @@ get_token() {
     --data-binary '{
       "type":        "token",
       "description": "'"$desc"'"
-    }' | jq -r '.token // empty')
+    }' | jq -r 'if type == "object" then
+                   .token else empty end')
 
   [ "$token" ] && {
     export API_TOKEN="$token"
@@ -123,13 +136,18 @@ rancher_projects() {
 # "<cluster>_ID"
 # "<cluster>_DEFAULT_ID"
 # "<cluster>_SYSTEM_ID"
+export_variables() {
+  eval "$(rancher_clusters | jq -r 'to_entries[] |
+    select(.key != "local" and
+          (.key | startswith("c-") | not)) |
+    "export \(.key | ascii_upcase)_ID=\"\(.value)\""
+    ')"
+  eval "$(rancher_projects | jq -r 'to_entries[] |
+    "export \(.key | ascii_upcase)_ID=\"\(.value)\""
+    ')"
+}
+export_variables
 
-eval "$(rancher_clusters | jq -r 'to_entries[] |
-  select(.key != "local" and
-        (.key | startswith("c-") | not)) |
-  "export \(.key | ascii_upcase)_ID=\"\(.value)\""
-  ')"
-
-eval "$(rancher_projects | jq -r 'to_entries[] |
-  "export \(.key | ascii_upcase)_ID=\"\(.value)\""
-  ')"
+command -v rancher &> /dev/null && {
+  alias r='rancher'
+}
